#![allow(unknown_lints)]
#![doc = "Peripheral access API for LPC176X5X microcontrollers (generated using svd2rust v0.30.2 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next]
svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.30.2/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![deny(dead_code)]
#![deny(improper_ctypes)]
#![deny(missing_docs)]
#![deny(no_mangle_generic_items)]
#![deny(non_shorthand_field_patterns)]
#![deny(overflowing_literals)]
#![deny(path_statements)]
#![deny(patterns_in_fns_without_body)]
#![deny(private_bounds)]
#![deny(private_interfaces)]
#![deny(unconditional_recursion)]
#![deny(unused_allocation)]
#![deny(unused_comparisons)]
#![deny(unused_parens)]
#![deny(while_true)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
use core::marker::PhantomData;
use core::ops::Deref;
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 5;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    #[cfg(feature = "wdt")]
    fn WDT();
    #[cfg(feature = "timer0")]
    fn TIMER0();
    #[cfg(feature = "timer1")]
    fn TIMER1();
    #[cfg(feature = "timer2")]
    fn TIMER2();
    #[cfg(feature = "timer3")]
    fn TIMER3();
    #[cfg(feature = "uart0")]
    fn UART0();
    #[cfg(feature = "uart1")]
    fn UART1();
    #[cfg(feature = "uart2")]
    fn UART2();
    #[cfg(feature = "uart3")]
    fn UART3();
    #[cfg(feature = "pwm1")]
    fn PWM1();
    #[cfg(feature = "i2c0")]
    fn I2C0();
    #[cfg(feature = "i2c1")]
    fn I2C1();
    #[cfg(feature = "i2c2")]
    fn I2C2();
    #[cfg(feature = "spi")]
    fn SPI();
    #[cfg(feature = "ssp0")]
    fn SSP0();
    #[cfg(feature = "ssp1")]
    fn SSP1();
    #[cfg(feature = "syscon")]
    fn PLL0();
    #[cfg(feature = "rtc")]
    fn RTC();
    #[cfg(feature = "syscon")]
    fn EINT0();
    #[cfg(feature = "syscon")]
    fn EINT1();
    #[cfg(feature = "syscon")]
    fn EINT2();
    #[cfg(feature = "syscon")]
    fn EINT3();
    #[cfg(feature = "adc")]
    fn ADC();
    #[cfg(feature = "syscon")]
    fn BOD();
    #[cfg(feature = "usb")]
    fn USB();
    #[cfg(feature = "can1")]
    fn CAN();
    #[cfg(feature = "gpdma")]
    fn DMA();
    #[cfg(feature = "i2s")]
    fn I2S();
    #[cfg(feature = "emac")]
    fn ENET();
    #[cfg(feature = "ritimer")]
    fn RIT();
    #[cfg(feature = "mcpwm")]
    fn MCPWM();
    #[cfg(feature = "qei")]
    fn QEI();
    #[cfg(feature = "syscon")]
    fn PLL1();
    #[cfg(feature = "usb")]
    fn USBACTIVITY();
    #[cfg(feature = "ccan")]
    fn CANACTIVITY();
}
#[doc(hidden)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 35] = [
    #[cfg(not(all(feature = "wdt",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "wdt")]
    Vector { _handler: WDT },
    #[cfg(not(all(feature = "timer0",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "timer0")]
    Vector { _handler: TIMER0 },
    #[cfg(not(all(feature = "timer1",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "timer1")]
    Vector { _handler: TIMER1 },
    #[cfg(not(all(feature = "timer2",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "timer2")]
    Vector { _handler: TIMER2 },
    #[cfg(not(all(feature = "timer3",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "timer3")]
    Vector { _handler: TIMER3 },
    #[cfg(not(all(feature = "uart0",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "uart0")]
    Vector { _handler: UART0 },
    #[cfg(not(all(feature = "uart1",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "uart1")]
    Vector { _handler: UART1 },
    #[cfg(not(all(feature = "uart2",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "uart2")]
    Vector { _handler: UART2 },
    #[cfg(not(all(feature = "uart3",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "uart3")]
    Vector { _handler: UART3 },
    #[cfg(not(all(feature = "pwm1",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "pwm1")]
    Vector { _handler: PWM1 },
    #[cfg(not(all(feature = "i2c0",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "i2c0")]
    Vector { _handler: I2C0 },
    #[cfg(not(all(feature = "i2c1",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "i2c1")]
    Vector { _handler: I2C1 },
    #[cfg(not(all(feature = "i2c2",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "i2c2")]
    Vector { _handler: I2C2 },
    #[cfg(not(all(feature = "spi",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "spi")]
    Vector { _handler: SPI },
    #[cfg(not(all(feature = "ssp0",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "ssp0")]
    Vector { _handler: SSP0 },
    #[cfg(not(all(feature = "ssp1",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "ssp1")]
    Vector { _handler: SSP1 },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: PLL0 },
    #[cfg(not(all(feature = "rtc",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "rtc")]
    Vector { _handler: RTC },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: EINT0 },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: EINT1 },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: EINT2 },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: EINT3 },
    #[cfg(not(all(feature = "adc",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "adc")]
    Vector { _handler: ADC },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: BOD },
    #[cfg(not(all(feature = "usb",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "usb")]
    Vector { _handler: USB },
    #[cfg(not(all(feature = "can1",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "can1")]
    Vector { _handler: CAN },
    #[cfg(not(all(feature = "gpdma",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "gpdma")]
    Vector { _handler: DMA },
    #[cfg(not(all(feature = "i2s",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "i2s")]
    Vector { _handler: I2S },
    #[cfg(not(all(feature = "emac",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "emac")]
    Vector { _handler: ENET },
    #[cfg(not(all(feature = "ritimer",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "ritimer")]
    Vector { _handler: RIT },
    #[cfg(not(all(feature = "mcpwm",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "mcpwm")]
    Vector { _handler: MCPWM },
    #[cfg(not(all(feature = "qei",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "qei")]
    Vector { _handler: QEI },
    #[cfg(not(all(feature = "syscon",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "syscon")]
    Vector { _handler: PLL1 },
    #[cfg(not(all(feature = "usb",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "usb")]
    Vector {
        _handler: USBACTIVITY,
    },
    #[cfg(not(all(feature = "ccan",)))]
    Vector { _reserved: 0 },
    #[cfg(feature = "ccan")]
    Vector {
        _handler: CANACTIVITY,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - WDT"]
    #[cfg(feature = "wdt")]
    WDT = 0,
    #[doc = "1 - TIMER0"]
    #[cfg(feature = "timer0")]
    TIMER0 = 1,
    #[doc = "2 - TIMER1"]
    #[cfg(feature = "timer1")]
    TIMER1 = 2,
    #[doc = "3 - TIMER2"]
    #[cfg(feature = "timer2")]
    TIMER2 = 3,
    #[doc = "4 - TIMER3"]
    #[cfg(feature = "timer3")]
    TIMER3 = 4,
    #[doc = "5 - UART0"]
    #[cfg(feature = "uart0")]
    UART0 = 5,
    #[doc = "6 - UART1"]
    #[cfg(feature = "uart1")]
    UART1 = 6,
    #[doc = "7 - UART2"]
    #[cfg(feature = "uart2")]
    UART2 = 7,
    #[doc = "8 - UART3"]
    #[cfg(feature = "uart3")]
    UART3 = 8,
    #[doc = "9 - PWM1"]
    #[cfg(feature = "pwm1")]
    PWM1 = 9,
    #[doc = "10 - I2C0"]
    #[cfg(feature = "i2c0")]
    I2C0 = 10,
    #[doc = "11 - I2C1"]
    #[cfg(feature = "i2c1")]
    I2C1 = 11,
    #[doc = "12 - I2C2"]
    #[cfg(feature = "i2c2")]
    I2C2 = 12,
    #[doc = "13 - SPI"]
    #[cfg(feature = "spi")]
    SPI = 13,
    #[doc = "14 - SSP0"]
    #[cfg(feature = "ssp0")]
    SSP0 = 14,
    #[doc = "15 - SSP1"]
    #[cfg(feature = "ssp1")]
    SSP1 = 15,
    #[doc = "16 - PLL0"]
    #[cfg(feature = "syscon")]
    PLL0 = 16,
    #[doc = "17 - RTC"]
    #[cfg(feature = "rtc")]
    RTC = 17,
    #[doc = "18 - EINT0"]
    #[cfg(feature = "syscon")]
    EINT0 = 18,
    #[doc = "19 - EINT1"]
    #[cfg(feature = "syscon")]
    EINT1 = 19,
    #[doc = "20 - EINT2"]
    #[cfg(feature = "syscon")]
    EINT2 = 20,
    #[doc = "21 - EINT3"]
    #[cfg(feature = "syscon")]
    EINT3 = 21,
    #[doc = "22 - ADC"]
    #[cfg(feature = "adc")]
    ADC = 22,
    #[doc = "23 - BOD"]
    #[cfg(feature = "syscon")]
    BOD = 23,
    #[doc = "24 - USB"]
    #[cfg(feature = "usb")]
    USB = 24,
    #[doc = "25 - CAN"]
    #[cfg(feature = "can1")]
    CAN = 25,
    #[doc = "26 - DMA"]
    #[cfg(feature = "gpdma")]
    DMA = 26,
    #[doc = "27 - I2S"]
    #[cfg(feature = "i2s")]
    I2S = 27,
    #[doc = "28 - ENET"]
    #[cfg(feature = "emac")]
    ENET = 28,
    #[doc = "29 - RIT"]
    #[cfg(feature = "ritimer")]
    RIT = 29,
    #[doc = "30 - MCPWM"]
    #[cfg(feature = "mcpwm")]
    MCPWM = 30,
    #[doc = "31 - QEI"]
    #[cfg(feature = "qei")]
    QEI = 31,
    #[doc = "32 - PLL1"]
    #[cfg(feature = "syscon")]
    PLL1 = 32,
    #[doc = "33 - USBActivity"]
    #[cfg(feature = "usb")]
    USBACTIVITY = 33,
    #[doc = "34 - CANActivity"]
    #[cfg(feature = "ccan")]
    CANACTIVITY = 34,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Watchdog Timer (WDT)"]
#[cfg(feature = "wdt")]
pub struct WDT {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "wdt")]
unsafe impl Send for WDT {}
#[cfg(feature = "wdt")]
impl WDT {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const wdt::RegisterBlock = 0x4000_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const wdt::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "wdt")]
impl Deref for WDT {
    type Target = wdt::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "wdt")]
impl core::fmt::Debug for WDT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WDT").finish()
    }
}
#[doc = "Watchdog Timer (WDT)"]
#[cfg(feature = "wdt")]
pub mod wdt;
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer0")]
pub struct TIMER0 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "timer0")]
unsafe impl Send for TIMER0 {}
#[cfg(feature = "timer0")]
impl TIMER0 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const timer0::RegisterBlock = 0x4000_4000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const timer0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "timer0")]
impl Deref for TIMER0 {
    type Target = timer0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "timer0")]
impl core::fmt::Debug for TIMER0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER0").finish()
    }
}
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer0")]
pub mod timer0;
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer1")]
pub struct TIMER1 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "timer1")]
unsafe impl Send for TIMER1 {}
#[cfg(feature = "timer1")]
impl TIMER1 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const timer0::RegisterBlock = 0x4000_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const timer0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "timer1")]
impl Deref for TIMER1 {
    type Target = timer0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "timer1")]
impl core::fmt::Debug for TIMER1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER1").finish()
    }
}
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer1")]
pub use self::timer0 as timer1;
#[doc = "UART0/2/3"]
#[cfg(feature = "uart0")]
pub struct UART0 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "uart0")]
unsafe impl Send for UART0 {}
#[cfg(feature = "uart0")]
impl UART0 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const uart0::RegisterBlock = 0x4000_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const uart0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "uart0")]
impl Deref for UART0 {
    type Target = uart0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "uart0")]
impl core::fmt::Debug for UART0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART0").finish()
    }
}
#[doc = "UART0/2/3"]
#[cfg(feature = "uart0")]
pub mod uart0;
#[doc = "UART1"]
#[cfg(feature = "uart1")]
pub struct UART1 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "uart1")]
unsafe impl Send for UART1 {}
#[cfg(feature = "uart1")]
impl UART1 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const uart1::RegisterBlock = 0x4001_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const uart1::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "uart1")]
impl Deref for UART1 {
    type Target = uart1::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "uart1")]
impl core::fmt::Debug for UART1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART1").finish()
    }
}
#[doc = "UART1"]
#[cfg(feature = "uart1")]
pub mod uart1;
#[doc = "Pulse Width Modulators (PWM1)"]
#[cfg(feature = "pwm1")]
pub struct PWM1 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "pwm1")]
unsafe impl Send for PWM1 {}
#[cfg(feature = "pwm1")]
impl PWM1 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const pwm1::RegisterBlock = 0x4001_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const pwm1::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "pwm1")]
impl Deref for PWM1 {
    type Target = pwm1::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "pwm1")]
impl core::fmt::Debug for PWM1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWM1").finish()
    }
}
#[doc = "Pulse Width Modulators (PWM1)"]
#[cfg(feature = "pwm1")]
pub mod pwm1;
#[doc = "I2C bus interface"]
#[cfg(feature = "i2c0")]
pub struct I2C0 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "i2c0")]
unsafe impl Send for I2C0 {}
#[cfg(feature = "i2c0")]
impl I2C0 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const i2c0::RegisterBlock = 0x4001_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const i2c0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "i2c0")]
impl Deref for I2C0 {
    type Target = i2c0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "i2c0")]
impl core::fmt::Debug for I2C0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C0").finish()
    }
}
#[doc = "I2C bus interface"]
#[cfg(feature = "i2c0")]
pub mod i2c0;
#[doc = "SPI"]
#[cfg(feature = "spi")]
pub struct SPI {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "spi")]
unsafe impl Send for SPI {}
#[cfg(feature = "spi")]
impl SPI {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const spi::RegisterBlock = 0x4002_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const spi::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "spi")]
impl Deref for SPI {
    type Target = spi::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "spi")]
impl core::fmt::Debug for SPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI").finish()
    }
}
#[doc = "SPI"]
#[cfg(feature = "spi")]
pub mod spi;
#[doc = "Real Time Clock (RTC)"]
#[cfg(feature = "rtc")]
pub struct RTC {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "rtc")]
unsafe impl Send for RTC {}
#[cfg(feature = "rtc")]
impl RTC {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const rtc::RegisterBlock = 0x4002_4000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const rtc::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "rtc")]
impl Deref for RTC {
    type Target = rtc::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "rtc")]
impl core::fmt::Debug for RTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RTC").finish()
    }
}
#[doc = "Real Time Clock (RTC)"]
#[cfg(feature = "rtc")]
pub mod rtc;
#[doc = "GPIO"]
#[cfg(feature = "gpioint")]
pub struct GPIOINT {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "gpioint")]
unsafe impl Send for GPIOINT {}
#[cfg(feature = "gpioint")]
impl GPIOINT {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const gpioint::RegisterBlock = 0x4002_8080 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const gpioint::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "gpioint")]
impl Deref for GPIOINT {
    type Target = gpioint::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "gpioint")]
impl core::fmt::Debug for GPIOINT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOINT").finish()
    }
}
#[doc = "GPIO"]
#[cfg(feature = "gpioint")]
pub mod gpioint;
#[doc = "Pin connect block"]
#[cfg(feature = "pinconnect")]
pub struct PINCONNECT {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "pinconnect")]
unsafe impl Send for PINCONNECT {}
#[cfg(feature = "pinconnect")]
impl PINCONNECT {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const pinconnect::RegisterBlock = 0x4002_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const pinconnect::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "pinconnect")]
impl Deref for PINCONNECT {
    type Target = pinconnect::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "pinconnect")]
impl core::fmt::Debug for PINCONNECT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PINCONNECT").finish()
    }
}
#[doc = "Pin connect block"]
#[cfg(feature = "pinconnect")]
pub mod pinconnect;
#[doc = "SSP1 controller"]
#[cfg(feature = "ssp1")]
pub struct SSP1 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "ssp1")]
unsafe impl Send for SSP1 {}
#[cfg(feature = "ssp1")]
impl SSP1 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const ssp1::RegisterBlock = 0x4003_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const ssp1::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "ssp1")]
impl Deref for SSP1 {
    type Target = ssp1::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "ssp1")]
impl core::fmt::Debug for SSP1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SSP1").finish()
    }
}
#[doc = "SSP1 controller"]
#[cfg(feature = "ssp1")]
pub mod ssp1;
#[doc = "Analog-to-Digital Converter (ADC)"]
#[cfg(feature = "adc")]
pub struct ADC {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "adc")]
unsafe impl Send for ADC {}
#[cfg(feature = "adc")]
impl ADC {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const adc::RegisterBlock = 0x4003_4000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const adc::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "adc")]
impl Deref for ADC {
    type Target = adc::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "adc")]
impl core::fmt::Debug for ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC").finish()
    }
}
#[doc = "Analog-to-Digital Converter (ADC)"]
#[cfg(feature = "adc")]
pub mod adc;
#[doc = "CAN acceptance filter RAM"]
#[cfg(feature = "canafram")]
pub struct CANAFRAM {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "canafram")]
unsafe impl Send for CANAFRAM {}
#[cfg(feature = "canafram")]
impl CANAFRAM {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const canafram::RegisterBlock = 0x4003_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const canafram::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "canafram")]
impl Deref for CANAFRAM {
    type Target = canafram::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "canafram")]
impl core::fmt::Debug for CANAFRAM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CANAFRAM").finish()
    }
}
#[doc = "CAN acceptance filter RAM"]
#[cfg(feature = "canafram")]
pub mod canafram;
#[doc = "CAN controller acceptance filter"]
#[cfg(feature = "canaf")]
pub struct CANAF {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "canaf")]
unsafe impl Send for CANAF {}
#[cfg(feature = "canaf")]
impl CANAF {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const canaf::RegisterBlock = 0x4003_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const canaf::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "canaf")]
impl Deref for CANAF {
    type Target = canaf::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "canaf")]
impl core::fmt::Debug for CANAF {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CANAF").finish()
    }
}
#[doc = "CAN controller acceptance filter"]
#[cfg(feature = "canaf")]
pub mod canaf;
#[doc = "Central CAN controller"]
#[cfg(feature = "ccan")]
pub struct CCAN {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "ccan")]
unsafe impl Send for CCAN {}
#[cfg(feature = "ccan")]
impl CCAN {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const ccan::RegisterBlock = 0x4004_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const ccan::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "ccan")]
impl Deref for CCAN {
    type Target = ccan::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "ccan")]
impl core::fmt::Debug for CCAN {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CCAN").finish()
    }
}
#[doc = "Central CAN controller"]
#[cfg(feature = "ccan")]
pub mod ccan;
#[doc = "CAN1 controller"]
#[cfg(feature = "can1")]
pub struct CAN1 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "can1")]
unsafe impl Send for CAN1 {}
#[cfg(feature = "can1")]
impl CAN1 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const can1::RegisterBlock = 0x4004_4000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const can1::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "can1")]
impl Deref for CAN1 {
    type Target = can1::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "can1")]
impl core::fmt::Debug for CAN1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAN1").finish()
    }
}
#[doc = "CAN1 controller"]
#[cfg(feature = "can1")]
pub mod can1;
#[doc = "CAN1 controller"]
#[cfg(feature = "can2")]
pub struct CAN2 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "can2")]
unsafe impl Send for CAN2 {}
#[cfg(feature = "can2")]
impl CAN2 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const can1::RegisterBlock = 0x4004_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const can1::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "can2")]
impl Deref for CAN2 {
    type Target = can1::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "can2")]
impl core::fmt::Debug for CAN2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAN2").finish()
    }
}
#[doc = "CAN1 controller"]
#[cfg(feature = "can2")]
pub use self::can1 as can2;
#[doc = "I2C bus interface"]
#[cfg(feature = "i2c1")]
pub struct I2C1 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "i2c1")]
unsafe impl Send for I2C1 {}
#[cfg(feature = "i2c1")]
impl I2C1 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const i2c0::RegisterBlock = 0x4005_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const i2c0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "i2c1")]
impl Deref for I2C1 {
    type Target = i2c0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "i2c1")]
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
#[doc = "I2C bus interface"]
#[cfg(feature = "i2c1")]
pub use self::i2c0 as i2c1;
#[doc = "SSP controller"]
#[cfg(feature = "ssp0")]
pub struct SSP0 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "ssp0")]
unsafe impl Send for SSP0 {}
#[cfg(feature = "ssp0")]
impl SSP0 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const ssp1::RegisterBlock = 0x4008_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const ssp1::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "ssp0")]
impl Deref for SSP0 {
    type Target = ssp1::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "ssp0")]
impl core::fmt::Debug for SSP0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SSP0").finish()
    }
}
#[doc = "SSP controller"]
#[cfg(feature = "ssp0")]
pub use self::ssp1 as ssp0;
#[doc = "Digital-to-Analog Converter (DAC)"]
#[cfg(feature = "dac")]
pub struct DAC {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "dac")]
unsafe impl Send for DAC {}
#[cfg(feature = "dac")]
impl DAC {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const dac::RegisterBlock = 0x4008_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const dac::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "dac")]
impl Deref for DAC {
    type Target = dac::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "dac")]
impl core::fmt::Debug for DAC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DAC").finish()
    }
}
#[doc = "Digital-to-Analog Converter (DAC)"]
#[cfg(feature = "dac")]
pub mod dac;
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer2")]
pub struct TIMER2 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "timer2")]
unsafe impl Send for TIMER2 {}
#[cfg(feature = "timer2")]
impl TIMER2 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const timer0::RegisterBlock = 0x4009_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const timer0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "timer2")]
impl Deref for TIMER2 {
    type Target = timer0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "timer2")]
impl core::fmt::Debug for TIMER2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER2").finish()
    }
}
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer2")]
pub use self::timer0 as timer2;
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer3")]
pub struct TIMER3 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "timer3")]
unsafe impl Send for TIMER3 {}
#[cfg(feature = "timer3")]
impl TIMER3 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const timer0::RegisterBlock = 0x4009_4000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const timer0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "timer3")]
impl Deref for TIMER3 {
    type Target = timer0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "timer3")]
impl core::fmt::Debug for TIMER3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER3").finish()
    }
}
#[doc = "Timer0/1/2/3"]
#[cfg(feature = "timer3")]
pub use self::timer0 as timer3;
#[doc = "UART0/2/3"]
#[cfg(feature = "uart2")]
pub struct UART2 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "uart2")]
unsafe impl Send for UART2 {}
#[cfg(feature = "uart2")]
impl UART2 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const uart0::RegisterBlock = 0x4009_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const uart0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "uart2")]
impl Deref for UART2 {
    type Target = uart0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "uart2")]
impl core::fmt::Debug for UART2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART2").finish()
    }
}
#[doc = "UART0/2/3"]
#[cfg(feature = "uart2")]
pub use self::uart0 as uart2;
#[doc = "UART0/2/3"]
#[cfg(feature = "uart3")]
pub struct UART3 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "uart3")]
unsafe impl Send for UART3 {}
#[cfg(feature = "uart3")]
impl UART3 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const uart0::RegisterBlock = 0x4009_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const uart0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "uart3")]
impl Deref for UART3 {
    type Target = uart0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "uart3")]
impl core::fmt::Debug for UART3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART3").finish()
    }
}
#[doc = "UART0/2/3"]
#[cfg(feature = "uart3")]
pub use self::uart0 as uart3;
#[doc = "I2C bus interface"]
#[cfg(feature = "i2c2")]
pub struct I2C2 {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "i2c2")]
unsafe impl Send for I2C2 {}
#[cfg(feature = "i2c2")]
impl I2C2 {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const i2c0::RegisterBlock = 0x400a_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const i2c0::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "i2c2")]
impl Deref for I2C2 {
    type Target = i2c0::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "i2c2")]
impl core::fmt::Debug for I2C2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C2").finish()
    }
}
#[doc = "I2C bus interface"]
#[cfg(feature = "i2c2")]
pub use self::i2c0 as i2c2;
#[doc = "I2S interface"]
#[cfg(feature = "i2s")]
pub struct I2S {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "i2s")]
unsafe impl Send for I2S {}
#[cfg(feature = "i2s")]
impl I2S {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const i2s::RegisterBlock = 0x400a_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const i2s::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "i2s")]
impl Deref for I2S {
    type Target = i2s::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "i2s")]
impl core::fmt::Debug for I2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2S").finish()
    }
}
#[doc = "I2S interface"]
#[cfg(feature = "i2s")]
pub mod i2s;
#[doc = "Repetitive Interrupt Timer (RIT)"]
#[cfg(feature = "ritimer")]
pub struct RITIMER {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "ritimer")]
unsafe impl Send for RITIMER {}
#[cfg(feature = "ritimer")]
impl RITIMER {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const ritimer::RegisterBlock = 0x400b_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const ritimer::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "ritimer")]
impl Deref for RITIMER {
    type Target = ritimer::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "ritimer")]
impl core::fmt::Debug for RITIMER {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RITIMER").finish()
    }
}
#[doc = "Repetitive Interrupt Timer (RIT)"]
#[cfg(feature = "ritimer")]
pub mod ritimer;
#[doc = "Motor Control PWM"]
#[cfg(feature = "mcpwm")]
pub struct MCPWM {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "mcpwm")]
unsafe impl Send for MCPWM {}
#[cfg(feature = "mcpwm")]
impl MCPWM {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const mcpwm::RegisterBlock = 0x400b_8000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const mcpwm::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "mcpwm")]
impl Deref for MCPWM {
    type Target = mcpwm::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "mcpwm")]
impl core::fmt::Debug for MCPWM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MCPWM").finish()
    }
}
#[doc = "Motor Control PWM"]
#[cfg(feature = "mcpwm")]
pub mod mcpwm;
#[doc = "Quadrature Encoder Interface (QEI)"]
#[cfg(feature = "qei")]
pub struct QEI {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "qei")]
unsafe impl Send for QEI {}
#[cfg(feature = "qei")]
impl QEI {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const qei::RegisterBlock = 0x400b_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const qei::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "qei")]
impl Deref for QEI {
    type Target = qei::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "qei")]
impl core::fmt::Debug for QEI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QEI").finish()
    }
}
#[doc = "Quadrature Encoder Interface (QEI)"]
#[cfg(feature = "qei")]
pub mod qei;
#[doc = "System and clock control"]
#[cfg(feature = "syscon")]
pub struct SYSCON {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "syscon")]
unsafe impl Send for SYSCON {}
#[cfg(feature = "syscon")]
impl SYSCON {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const syscon::RegisterBlock = 0x400f_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const syscon::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "syscon")]
impl Deref for SYSCON {
    type Target = syscon::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "syscon")]
impl core::fmt::Debug for SYSCON {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSCON").finish()
    }
}
#[doc = "System and clock control"]
#[cfg(feature = "syscon")]
pub mod syscon;
#[doc = "Ethernet"]
#[cfg(feature = "emac")]
pub struct EMAC {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "emac")]
unsafe impl Send for EMAC {}
#[cfg(feature = "emac")]
impl EMAC {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const emac::RegisterBlock = 0x5000_0000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const emac::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "emac")]
impl Deref for EMAC {
    type Target = emac::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "emac")]
impl core::fmt::Debug for EMAC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EMAC").finish()
    }
}
#[doc = "Ethernet"]
#[cfg(feature = "emac")]
pub mod emac;
#[doc = "General purpose DMA controller"]
#[cfg(feature = "gpdma")]
pub struct GPDMA {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "gpdma")]
unsafe impl Send for GPDMA {}
#[cfg(feature = "gpdma")]
impl GPDMA {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const gpdma::RegisterBlock = 0x5000_4000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const gpdma::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "gpdma")]
impl Deref for GPDMA {
    type Target = gpdma::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "gpdma")]
impl core::fmt::Debug for GPDMA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPDMA").finish()
    }
}
#[doc = "General purpose DMA controller"]
#[cfg(feature = "gpdma")]
pub mod gpdma;
#[doc = "USB device/host/OTG controller"]
#[cfg(feature = "usb")]
pub struct USB {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "usb")]
unsafe impl Send for USB {}
#[cfg(feature = "usb")]
impl USB {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const usb::RegisterBlock = 0x5000_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const usb::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "usb")]
impl Deref for USB {
    type Target = usb::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "usb")]
impl core::fmt::Debug for USB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB").finish()
    }
}
#[doc = "USB device/host/OTG controller"]
#[cfg(feature = "usb")]
pub mod usb;
#[doc = "General Purpose I/O"]
#[cfg(feature = "gpio")]
pub struct GPIO {
    _marker: PhantomData<*const ()>,
}
#[cfg(feature = "gpio")]
unsafe impl Send for GPIO {}
#[cfg(feature = "gpio")]
impl GPIO {
    #[doc = r"Pointer to the register block"]
    pub const PTR: *const gpio::RegisterBlock = 0x2009_c000 as *const _;
    #[doc = r"Return the pointer to the register block"]
    #[inline(always)]
    pub const fn ptr() -> *const gpio::RegisterBlock {
        Self::PTR
    }
    #[doc = r" Steal an instance of this peripheral"]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Ensure that the new instance of the peripheral cannot be used in a way"]
    #[doc = r" that may race with any existing instances, for example by only"]
    #[doc = r" accessing read-only or write-only registers, or by consuming the"]
    #[doc = r" original peripheral and using critical sections to coordinate"]
    #[doc = r" access between multiple new instances."]
    #[doc = r""]
    #[doc = r" Additionally, other software such as HALs may rely on only one"]
    #[doc = r" peripheral instance existing to ensure memory safety; ensure"]
    #[doc = r" no stolen instances are passed to such software."]
    pub unsafe fn steal() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}
#[cfg(feature = "gpio")]
impl Deref for GPIO {
    type Target = gpio::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
#[cfg(feature = "gpio")]
impl core::fmt::Debug for GPIO {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIO").finish()
    }
}
#[doc = "General Purpose I/O"]
#[cfg(feature = "gpio")]
pub mod gpio;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "WDT"]
    #[cfg(feature = "wdt")]
    pub WDT: WDT,
    #[doc = "TIMER0"]
    #[cfg(feature = "timer0")]
    pub TIMER0: TIMER0,
    #[doc = "TIMER1"]
    #[cfg(feature = "timer1")]
    pub TIMER1: TIMER1,
    #[doc = "UART0"]
    #[cfg(feature = "uart0")]
    pub UART0: UART0,
    #[doc = "UART1"]
    #[cfg(feature = "uart1")]
    pub UART1: UART1,
    #[doc = "PWM1"]
    #[cfg(feature = "pwm1")]
    pub PWM1: PWM1,
    #[doc = "I2C0"]
    #[cfg(feature = "i2c0")]
    pub I2C0: I2C0,
    #[doc = "SPI"]
    #[cfg(feature = "spi")]
    pub SPI: SPI,
    #[doc = "RTC"]
    #[cfg(feature = "rtc")]
    pub RTC: RTC,
    #[doc = "GPIOINT"]
    #[cfg(feature = "gpioint")]
    pub GPIOINT: GPIOINT,
    #[doc = "PINCONNECT"]
    #[cfg(feature = "pinconnect")]
    pub PINCONNECT: PINCONNECT,
    #[doc = "SSP1"]
    #[cfg(feature = "ssp1")]
    pub SSP1: SSP1,
    #[doc = "ADC"]
    #[cfg(feature = "adc")]
    pub ADC: ADC,
    #[doc = "CANAFRAM"]
    #[cfg(feature = "canafram")]
    pub CANAFRAM: CANAFRAM,
    #[doc = "CANAF"]
    #[cfg(feature = "canaf")]
    pub CANAF: CANAF,
    #[doc = "CCAN"]
    #[cfg(feature = "ccan")]
    pub CCAN: CCAN,
    #[doc = "CAN1"]
    #[cfg(feature = "can1")]
    pub CAN1: CAN1,
    #[doc = "CAN2"]
    #[cfg(feature = "can2")]
    pub CAN2: CAN2,
    #[doc = "I2C1"]
    #[cfg(feature = "i2c1")]
    pub I2C1: I2C1,
    #[doc = "SSP0"]
    #[cfg(feature = "ssp0")]
    pub SSP0: SSP0,
    #[doc = "DAC"]
    #[cfg(feature = "dac")]
    pub DAC: DAC,
    #[doc = "TIMER2"]
    #[cfg(feature = "timer2")]
    pub TIMER2: TIMER2,
    #[doc = "TIMER3"]
    #[cfg(feature = "timer3")]
    pub TIMER3: TIMER3,
    #[doc = "UART2"]
    #[cfg(feature = "uart2")]
    pub UART2: UART2,
    #[doc = "UART3"]
    #[cfg(feature = "uart3")]
    pub UART3: UART3,
    #[doc = "I2C2"]
    #[cfg(feature = "i2c2")]
    pub I2C2: I2C2,
    #[doc = "I2S"]
    #[cfg(feature = "i2s")]
    pub I2S: I2S,
    #[doc = "RITIMER"]
    #[cfg(feature = "ritimer")]
    pub RITIMER: RITIMER,
    #[doc = "MCPWM"]
    #[cfg(feature = "mcpwm")]
    pub MCPWM: MCPWM,
    #[doc = "QEI"]
    #[cfg(feature = "qei")]
    pub QEI: QEI,
    #[doc = "SYSCON"]
    #[cfg(feature = "syscon")]
    pub SYSCON: SYSCON,
    #[doc = "EMAC"]
    #[cfg(feature = "emac")]
    pub EMAC: EMAC,
    #[doc = "GPDMA"]
    #[cfg(feature = "gpdma")]
    pub GPDMA: GPDMA,
    #[doc = "USB"]
    #[cfg(feature = "usb")]
    pub USB: USB,
    #[doc = "GPIO"]
    #[cfg(feature = "gpio")]
    pub GPIO: GPIO,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            #[cfg(feature = "wdt")]
            WDT: WDT {
                _marker: PhantomData,
            },
            #[cfg(feature = "timer0")]
            TIMER0: TIMER0 {
                _marker: PhantomData,
            },
            #[cfg(feature = "timer1")]
            TIMER1: TIMER1 {
                _marker: PhantomData,
            },
            #[cfg(feature = "uart0")]
            UART0: UART0 {
                _marker: PhantomData,
            },
            #[cfg(feature = "uart1")]
            UART1: UART1 {
                _marker: PhantomData,
            },
            #[cfg(feature = "pwm1")]
            PWM1: PWM1 {
                _marker: PhantomData,
            },
            #[cfg(feature = "i2c0")]
            I2C0: I2C0 {
                _marker: PhantomData,
            },
            #[cfg(feature = "spi")]
            SPI: SPI {
                _marker: PhantomData,
            },
            #[cfg(feature = "rtc")]
            RTC: RTC {
                _marker: PhantomData,
            },
            #[cfg(feature = "gpioint")]
            GPIOINT: GPIOINT {
                _marker: PhantomData,
            },
            #[cfg(feature = "pinconnect")]
            PINCONNECT: PINCONNECT {
                _marker: PhantomData,
            },
            #[cfg(feature = "ssp1")]
            SSP1: SSP1 {
                _marker: PhantomData,
            },
            #[cfg(feature = "adc")]
            ADC: ADC {
                _marker: PhantomData,
            },
            #[cfg(feature = "canafram")]
            CANAFRAM: CANAFRAM {
                _marker: PhantomData,
            },
            #[cfg(feature = "canaf")]
            CANAF: CANAF {
                _marker: PhantomData,
            },
            #[cfg(feature = "ccan")]
            CCAN: CCAN {
                _marker: PhantomData,
            },
            #[cfg(feature = "can1")]
            CAN1: CAN1 {
                _marker: PhantomData,
            },
            #[cfg(feature = "can2")]
            CAN2: CAN2 {
                _marker: PhantomData,
            },
            #[cfg(feature = "i2c1")]
            I2C1: I2C1 {
                _marker: PhantomData,
            },
            #[cfg(feature = "ssp0")]
            SSP0: SSP0 {
                _marker: PhantomData,
            },
            #[cfg(feature = "dac")]
            DAC: DAC {
                _marker: PhantomData,
            },
            #[cfg(feature = "timer2")]
            TIMER2: TIMER2 {
                _marker: PhantomData,
            },
            #[cfg(feature = "timer3")]
            TIMER3: TIMER3 {
                _marker: PhantomData,
            },
            #[cfg(feature = "uart2")]
            UART2: UART2 {
                _marker: PhantomData,
            },
            #[cfg(feature = "uart3")]
            UART3: UART3 {
                _marker: PhantomData,
            },
            #[cfg(feature = "i2c2")]
            I2C2: I2C2 {
                _marker: PhantomData,
            },
            #[cfg(feature = "i2s")]
            I2S: I2S {
                _marker: PhantomData,
            },
            #[cfg(feature = "ritimer")]
            RITIMER: RITIMER {
                _marker: PhantomData,
            },
            #[cfg(feature = "mcpwm")]
            MCPWM: MCPWM {
                _marker: PhantomData,
            },
            #[cfg(feature = "qei")]
            QEI: QEI {
                _marker: PhantomData,
            },
            #[cfg(feature = "syscon")]
            SYSCON: SYSCON {
                _marker: PhantomData,
            },
            #[cfg(feature = "emac")]
            EMAC: EMAC {
                _marker: PhantomData,
            },
            #[cfg(feature = "gpdma")]
            GPDMA: GPDMA {
                _marker: PhantomData,
            },
            #[cfg(feature = "usb")]
            USB: USB {
                _marker: PhantomData,
            },
            #[cfg(feature = "gpio")]
            GPIO: GPIO {
                _marker: PhantomData,
            },
        }
    }
}
